fn main() {
    [
        None,
        None,
        Some(DmmfInputType {
            name: "StringFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "contains",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "startsWith",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "endsWith",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: false,
                    input_types: [
                        DmmfTypeReference {
                            typ: "String",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedStringFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        Some(DmmfInputType {
            name: "StringNullableFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "String",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "String",
                            namespace: None,
                            location: Scalar,
                            is_list: true,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "String",
                            namespace: None,
                            location: Scalar,
                            is_list: true,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "contains",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "startsWith",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "endsWith",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "String",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedStringNullableFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        None,
        None,
        Some(DmmfInputType {
            name: "NestedStringFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "contains",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "startsWith",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "endsWith",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: false,
                    input_types: [
                        DmmfTypeReference {
                            typ: "String",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedStringFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        Some(DmmfInputType {
            name: "NestedStringNullableFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "String",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "String",
                            namespace: None,
                            location: Scalar,
                            is_list: true,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "String",
                            namespace: None,
                            location: Scalar,
                            is_list: true,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "contains",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "startsWith",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "endsWith",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "String",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "String",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedStringNullableFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        None,
        None,
        Some(DmmfInputType {
            name: "DateTimeFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: false,
                    input_types: [
                        DmmfTypeReference {
                            typ: "DateTime",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedDateTimeFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        None,
        None,
        None,
        Some(DmmfInputType {
            name: "NestedDateTimeFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "DateTime",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: false,
                    input_types: [
                        DmmfTypeReference {
                            typ: "DateTime",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedDateTimeFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some(DmmfInputType {
            name: "IntFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: false,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Int",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedIntFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        Some(DmmfInputType {
            name: "IntNullableFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Int",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Int",
                            namespace: None,
                            location: Scalar,
                            is_list: true,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Int",
                            namespace: None,
                            location: Scalar,
                            is_list: true,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Int",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedIntNullableFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        None,
        None,
        Some(DmmfInputType {
            name: "NestedIntFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: false,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Int",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedIntFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        Some(DmmfInputType {
            name: "NestedIntNullableFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Int",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Int",
                            namespace: None,
                            location: Scalar,
                            is_list: true,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Int",
                            namespace: None,
                            location: Scalar,
                            is_list: true,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Int",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Int",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedIntNullableFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some(DmmfInputType {
            name: "FloatFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: false,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Float",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedFloatFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        None,
        None,
        None,
        Some(DmmfInputType {
            name: "NestedFloatFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: true,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: false,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Float",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedFloatFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
        Some(DmmfInputType {
            name: "NestedFloatNullableFilter",
            constraints: DmmfInputTypeConstraints {
                max_num_fields: None,
                min_num_fields: None,
            },
            fields: [
                DmmfInputField {
                    name: "equals",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Float",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "in",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Float",
                            namespace: None,
                            location: Scalar,
                            is_list: true,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "notIn",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Float",
                            namespace: None,
                            location: Scalar,
                            is_list: true,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "lte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gt",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "gte",
                    is_required: false,
                    is_nullable: false,
                    input_types: [DmmfTypeReference {
                        typ: "Float",
                        namespace: None,
                        location: Scalar,
                        is_list: false,
                    }],
                    deprecation: None,
                },
                DmmfInputField {
                    name: "not",
                    is_required: false,
                    is_nullable: true,
                    input_types: [
                        DmmfTypeReference {
                            typ: "Float",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "NestedFloatNullableFilter",
                            namespace: Some("prisma"),
                            location: InputObjectTypes,
                            is_list: false,
                        },
                        DmmfTypeReference {
                            typ: "Null",
                            namespace: None,
                            location: Scalar,
                            is_list: false,
                        },
                    ],
                    deprecation: None,
                },
            ],
        }),
    ]
}
